jaffle_shop:
  target: dev
  outputs:
    dev:
      schema: gaborratky
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "sql/protocolv1/o/{{ env_var('DBT_ORG_ID') }}/{{ env_var('DBT_CLUSTER_ID') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 1
      type: databricks
    logfood:
      catalog: hive_metastore
      schema: gaborratky
      host: adb-2548836972759138.18.azuredatabricks.net
      http_path: /sql/1.0/endpoints/c74767a0dca603eb
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 1
      type: databricks
    snowflake:
      account: abc123
      user: johndoe
      password: deadbeef
      role: SYSADMIN
      database: REPORTING
      warehouse: ANALYTICS
      schema: ANALYTICS
      threads: 1
      type: snowflake
